# Generated by Django 2.2.6 on 2019-11-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
